language: node_js
sudo: required
node_js: stable
cache:
  directories:
  - node_modules
branches:
  except:
  - gh-pages
before_deploy:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  on:
    branch: master
dist: trusty